import type { ExperienceItem, Project, Skill } from "@/types/portfolio";

export const PROJECTS: Project[] = [
  {
    id: "proj-001",
    slug: "ds1-developers-realm",
    name: "DS1 - The Developer's Realm",
    description: "Portfolio inmersivo con enfoque full stack, game loop y arquitectura modular.",
    longDescription:
      "Una experiencia web editorial e interactiva que integra portfolio, sistema de navegación temática y base para un mini juego de progresión.",
    technologies: ["Next.js", "TypeScript", "Tailwind", "Framer Motion"],
    category: "Full Stack",
    year: 2026,
    status: "In Progress",
    githubUrl: "https://github.com/gaspardoval",
    liveUrl: "https://example.com/ds1-realm",
    imageUrl: "/images/projects/ds1-realm.svg",
    featured: true,
    problem:
      "Necesidad de demostrar capacidades técnicas y creativas en un único producto profesional.",
    solution:
      "Diseño de plataforma modular que conecta presentación profesional con sistemas interactivos y escalabilidad backend.",
    architecture: [
      "App Router segmentado por dominios",
      "Capa de servicios separada de UI",
      "Estrategia de datos lista para migrar a Prisma",
    ],
    results: [
      "Base visual premium implementada",
      "Navegación responsive y accesible",
      "Rendimiento inicial optimizado",
    ],
  },
  {
    id: "proj-002",
    slug: "orbital-command",
    name: "Orbital Command",
    description: "Dashboard de operaciones en tiempo real para eventos de telemetría.",
    longDescription:
      "Sistema de monitoreo con flujos de datos en tiempo real, alertas y panel administrativo.",
    technologies: ["React", "Node.js", "PostgreSQL", "Socket.IO"],
    category: "Web Development",
    year: 2025,
    status: "Completed",
    githubUrl: "https://github.com/gaspardoval/orbital-command",
    liveUrl: "https://example.com/orbital-command",
    imageUrl: "/images/projects/orbital-command.svg",
    featured: true,
    problem: "Visualizar datos críticos con baja latencia y trazabilidad operativa.",
    solution: "Arquitectura event-driven con almacenamiento relacional y vistas de alta legibilidad.",
    architecture: ["API REST + WebSocket", "PostgreSQL", "RBAC para administración"],
    results: ["Tiempo de respuesta estable", "Escalabilidad horizontal de workers"],
  },
  {
    id: "proj-003",
    slug: "last-builder-prototype",
    name: "The Last Builder Prototype",
    description: "Prototipo de economía incremental para navegador con progreso persistente.",
    longDescription:
      "Loop de exploración, recolección, construcción y automatización diseñado para sesiones cortas.",
    technologies: ["Phaser", "TypeScript", "Zustand"],
    category: "Game Development",
    year: 2026,
    status: "In Progress",
    githubUrl: "https://github.com/gaspardoval/last-builder-prototype",
    liveUrl: "https://example.com/last-builder",
    imageUrl: "/images/projects/last-builder.svg",
    featured: false,
    problem: "Convertir progresión compleja en una experiencia clara y adictiva.",
    solution: "Diseño de economía modular con feedback inmediato y quests por hitos.",
    architecture: ["Game state centralizado", "Config de balance versionada", "Persistencia de perfil"],
    results: ["Loop principal validado", "Balance preliminar de recursos"],
  },
  {
    id: "proj-004",
    slug: "mint-pass-lab",
    name: "Mint Pass Lab",
    description: "Experimento de minting en testnet para credenciales de logros.",
    longDescription:
      "Implementación de contrato ERC-721 con metadata de achievements y flujo wallet opcional.",
    technologies: ["Solidity", "Hardhat", "viem", "OpenZeppelin"],
    category: "Web3",
    year: 2025,
    status: "Completed",
    githubUrl: "https://github.com/gaspardoval/mint-pass-lab",
    liveUrl: "https://example.com/mint-pass-lab",
    imageUrl: "/images/projects/mint-pass-lab.svg",
    featured: false,
    problem: "Emitir credenciales verificables sin comprometer UX ni seguridad.",
    solution: "Contrato con permisos de minteo acotados y flujo wallet no intrusivo.",
    architecture: ["ERC-721 base", "Scripts de deploy por red", "Integración frontend desacoplada"],
    results: ["Mint en testnet funcional", "Metadatos validados"],
  },
  {
    id: "proj-005",
    slug: "shader-atlas",
    name: "Shader Atlas",
    description: "Exploración de visuales generativos para interfaces inmersivas.",
    longDescription:
      "Colección de escenas reactivas optimizadas para integrarse como fondos interactivos en productos web.",
    technologies: ["Three.js", "R3F", "GLSL"],
    category: "Creative Coding",
    year: 2024,
    status: "Completed",
    githubUrl: "https://github.com/gaspardoval/shader-atlas",
    liveUrl: "https://example.com/shader-atlas",
    imageUrl: "/images/projects/shader-atlas.svg",
    featured: false,
    problem: "Crear identidad visual dinámica sin comprometer performance.",
    solution: "Escenas abstractas livianas con control de densidad por dispositivo.",
    architecture: ["Render condicional por viewport", "Lazy loading de escenas"],
    results: ["60fps en equipos medios", "Integración reusable"],
  },
];

export const SKILLS: Skill[] = [
  {
    id: "skill-001",
    name: "HTML",
    category: "Frontend",
    level: "Advanced",
    years: 6,
    description: "Arquitectura semántica, SEO técnico y accesibilidad base.",
    relatedProjectSlugs: ["ds1-developers-realm", "orbital-command"],
  },
  {
    id: "skill-002",
    name: "CSS",
    category: "Frontend",
    level: "Advanced",
    years: 6,
    description: "Sistemas de diseño, layouts complejos y animación de interfaz.",
    relatedProjectSlugs: ["ds1-developers-realm", "shader-atlas"],
  },
  {
    id: "skill-003",
    name: "JavaScript",
    category: "Frontend",
    level: "Advanced",
    years: 6,
    description: "Lógica de producto y arquitectura de componentes interactivos.",
    relatedProjectSlugs: ["orbital-command", "last-builder-prototype"],
  },
  {
    id: "skill-004",
    name: "TypeScript",
    category: "Frontend",
    level: "Advanced",
    years: 4,
    description: "Tipado estricto y contratos de dominio mantenibles.",
    relatedProjectSlugs: ["ds1-developers-realm", "last-builder-prototype"],
  },
  {
    id: "skill-005",
    name: "React",
    category: "Frontend",
    level: "Advanced",
    years: 4,
    description: "Interfaces de alto rendimiento con composición escalable.",
    relatedProjectSlugs: ["ds1-developers-realm", "orbital-command"],
  },
  {
    id: "skill-006",
    name: "Next.js",
    category: "Frontend",
    level: "Advanced",
    years: 3,
    description: "SSR, App Router y optimización de entrega web.",
    relatedProjectSlugs: ["ds1-developers-realm"],
  },
  {
    id: "skill-007",
    name: "Node.js",
    category: "Backend",
    level: "Advanced",
    years: 4,
    description: "APIs, jobs y servicios de integración.",
    relatedProjectSlugs: ["orbital-command", "ds1-developers-realm"],
  },
  {
    id: "skill-008",
    name: "Express",
    category: "Backend",
    level: "Intermediate",
    years: 3,
    description: "Servicios REST y middleware de validación.",
    relatedProjectSlugs: ["orbital-command"],
  },
  {
    id: "skill-009",
    name: "C#",
    category: "Game Development",
    level: "Intermediate",
    years: 3,
    description: "Scripting de gameplay y herramientas internas.",
    relatedProjectSlugs: ["last-builder-prototype"],
  },
  {
    id: "skill-010",
    name: "Java",
    category: "Backend",
    level: "Intermediate",
    years: 2,
    description: "Desarrollo de servicios académicos y fundamentos de arquitectura.",
    relatedProjectSlugs: [],
  },
  {
    id: "skill-011",
    name: "SQL",
    category: "Database",
    level: "Advanced",
    years: 4,
    description: "Modelado relacional y consultas optimizadas.",
    relatedProjectSlugs: ["orbital-command", "ds1-developers-realm"],
  },
  {
    id: "skill-012",
    name: "MySQL",
    category: "Database",
    level: "Intermediate",
    years: 3,
    description: "Diseño de esquemas y mantenimiento de datos transaccionales.",
    relatedProjectSlugs: ["orbital-command"],
  },
  {
    id: "skill-013",
    name: "PostgreSQL",
    category: "Database",
    level: "Advanced",
    years: 3,
    description: "Índices, integridad y escalabilidad en producción.",
    relatedProjectSlugs: ["orbital-command", "ds1-developers-realm"],
  },
  {
    id: "skill-014",
    name: "Unity",
    category: "Game Development",
    level: "Intermediate",
    years: 3,
    description: "Prototipado rápido de mecánicas y UX in-game.",
    relatedProjectSlugs: ["last-builder-prototype"],
  },
  {
    id: "skill-015",
    name: "Godot",
    category: "Game Development",
    level: "Intermediate",
    years: 2,
    description: "Estructura de escenas y sistemas de progresión 2D.",
    relatedProjectSlugs: ["last-builder-prototype"],
  },
  {
    id: "skill-016",
    name: "Git",
    category: "Tools",
    level: "Advanced",
    years: 6,
    description: "Versionado, branching y flujos colaborativos.",
    relatedProjectSlugs: ["ds1-developers-realm"],
  },
  {
    id: "skill-017",
    name: "GitHub",
    category: "Tools",
    level: "Advanced",
    years: 6,
    description: "CI básico, revisión de código y documentación.",
    relatedProjectSlugs: ["ds1-developers-realm"],
  },
  {
    id: "skill-018",
    name: "Blender",
    category: "Design",
    level: "Intermediate",
    years: 2,
    description: "Modelado y assets optimizados para web interactiva.",
    relatedProjectSlugs: ["shader-atlas"],
  },
  {
    id: "skill-019",
    name: "Three.js",
    category: "Frontend",
    level: "Intermediate",
    years: 2,
    description: "Escenas interactivas livianas para experiencias premium.",
    relatedProjectSlugs: ["shader-atlas", "ds1-developers-realm"],
  },
  {
    id: "skill-020",
    name: "Web3",
    category: "Web3",
    level: "Intermediate",
    years: 2,
    description: "Wallet flows, testnets y smart contracts básicos.",
    relatedProjectSlugs: ["mint-pass-lab"],
  },
];

export const EXPERIENCES: ExperienceItem[] = [
  {
    id: "exp-001",
    role: "Full Stack Developer",
    company: "Freelance",
    startDate: "2023-01",
    endDate: "Present",
    summary:
      "Diseño y desarrollo de productos web de principio a fin, con foco en experiencia de usuario y mantenibilidad.",
    highlights: [
      "Arquitecturas modulares con Next.js y Node.js",
      "Implementación de sistemas de datos relacionales",
      "Optimización de performance y UX",
    ],
  },
  {
    id: "exp-002",
    role: "Game Developer",
    company: "Independent Projects",
    startDate: "2022-01",
    endDate: "Present",
    summary:
      "Creación de prototipos jugables 2D y sistemas de progresión para web.",
    highlights: [
      "Diseño de loops de economía incremental",
      "Implementación de prototipos con Phaser y Unity",
      "Testing de balance y feedback de jugador",
    ],
  },
  {
    id: "exp-003",
    role: "Creative Technologist",
    company: "Lab + Personal R&D",
    startDate: "2021-01",
    endDate: "Present",
    summary:
      "Exploración de visuales interactivos, narrativa digital y nuevas interfaces web.",
    highlights: [
      "Experimentos con Three.js y shaders",
      "Integración de motion systems en UI",
      "Prototipos de interacción inmersiva",
    ],
  },
];
